---
- name: Start Minecraft Server
  systemd:
    name: minecraft
    enabled: true
    state: started

- name: Verify server is up
  shell: tail {{ minecraft_directory }}/logs/latest.log
  register: server_status
  until: server_status.stdout.find('Done') != -1
  retries: 10
  delay: 20
